# Generated by Django 4.2.3 on 2023-07-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kviz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='player_id',
            new_name='player',
        ),
    ]
