# Generated by Django 4.2.3 on 2023-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kviz_app', '0002_rename_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='correct',
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
